name: yummy
description: "Yummy is a food platform for customers to order food from restaurants."

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/categories/
    - assets/food/
    - assets/profile_pics/
    - assets/restaurants/
