// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNAgzqIzsoPLIGS6O5AHsg8Htr2V0hEkc',
    appId: '1:1058987243975:web:f4bed650adc13ccdac81e2',
    messagingSenderId: '1058987243975',
    projectId: 'yummy-756be',
    authDomain: 'yummy-756be.firebaseapp.com',
    storageBucket: 'yummy-756be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFqnzez8bq16ZGBzLy6U39EIvXoIz12SQ',
    appId: '1:1058987243975:android:73987abd638c15d1ac81e2',
    messagingSenderId: '1058987243975',
    projectId: 'yummy-756be',
    storageBucket: 'yummy-756be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnE6Ncr0-bct-xGnaA6B_Lwt41tWJZemI',
    appId: '1:1058987243975:ios:d31425271b7e6c06ac81e2',
    messagingSenderId: '1058987243975',
    projectId: 'yummy-756be',
    storageBucket: 'yummy-756be.appspot.com',
    iosBundleId: 'com.example.yummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnE6Ncr0-bct-xGnaA6B_Lwt41tWJZemI',
    appId: '1:1058987243975:ios:d31425271b7e6c06ac81e2',
    messagingSenderId: '1058987243975',
    projectId: 'yummy-756be',
    storageBucket: 'yummy-756be.appspot.com',
    iosBundleId: 'com.example.yummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNAgzqIzsoPLIGS6O5AHsg8Htr2V0hEkc',
    appId: '1:1058987243975:web:e856a002349939eaac81e2',
    messagingSenderId: '1058987243975',
    projectId: 'yummy-756be',
    authDomain: 'yummy-756be.firebaseapp.com',
    storageBucket: 'yummy-756be.appspot.com',
  );
}
